table Calendario
	lineageTag: bd00cf37-432c-4b09-916f-a4b5ec20b958

	column Fecha
		dataType: dateTime
		lineageTag: 333418c3-cca3-4e9c-99a9-50b7ba94bba9
		summarizeBy: none
		sourceColumn: Fecha

		variation Variación
			isDefault
			relationship: 58a0a1ae-90d4-42d6-80f9-da65c59b322a
			defaultHierarchy: LocalDateTable_443c4952-3be2-4d8e-9f3a-e296ce6f7531.'Jerarquía de fechas'

	column Anio
		dataType: int64
		lineageTag: 68c1f399-a621-45ed-ad49-187980b20267
		summarizeBy: sum
		sourceColumn: Anio

		annotation SummarizationSetBy = Automatic

	column Mes
		dataType: int64
		lineageTag: e8e7478b-ad3a-44be-a666-53bd33842fd3
		summarizeBy: sum
		sourceColumn: Mes

		annotation SummarizationSetBy = Automatic

	column NombreMes
		dataType: string
		lineageTag: 819ec07e-aeaa-41be-b041-46e0e35f5e87
		summarizeBy: none
		sourceColumn: NombreMes

	column Dia
		dataType: int64
		lineageTag: 2aeac824-24b5-4fa3-984f-e165f5b9e741
		summarizeBy: sum
		sourceColumn: Dia

		annotation SummarizationSetBy = Automatic

	column NumeroDia
		dataType: int64
		lineageTag: 5296c3ee-b018-4223-acb2-407e697a6992
		summarizeBy: sum
		sourceColumn: NumeroDia

		annotation SummarizationSetBy = Automatic

	column OrdenDia
		dataType: int64
		lineageTag: 0faca9b8-95a2-4e21-912c-411c64e8bc0e
		summarizeBy: sum
		sourceColumn: OrdenDia

		annotation SummarizationSetBy = Automatic

	column NombreDia
		dataType: string
		lineageTag: 2db8f467-26d1-48ad-8dae-ed42b08dfc59
		summarizeBy: none
		sourceColumn: NombreDia
		sortByColumn: OrdenDia

	column Semana
		dataType: int64
		lineageTag: 0f835678-bf40-4db3-9b79-0a022fa3f052
		summarizeBy: sum
		sourceColumn: Semana

		annotation SummarizationSetBy = Automatic

	partition Calendario = m
		mode: import
		source =
				let
				    Inicio = #date(2017, 7, 24),
				    Fin = #date(2017, 7, 30),
				    Dias = List.Dates(Inicio, Duration.Days(Fin - Inicio) + 1, #duration(1, 0, 0, 0)),
				    Origen = Table.FromList(Dias, Splitter.SplitByNothing(), {"Fecha"}),
				    ConFecha = Table.TransformColumnTypes(Origen, {{"Fecha", type datetime}}),
				    ConAnio = Table.AddColumn(ConFecha, "Anio", each Date.Year([Fecha]), Int64.Type),
				    ConMes = Table.AddColumn(ConAnio, "Mes", each Date.Month([Fecha]), Int64.Type),
				    ConNombreMes = Table.AddColumn(ConMes, "NombreMes", each Date.MonthName([Fecha]), type text),
				    ConDia = Table.AddColumn(ConNombreMes, "Dia", each Date.Day([Fecha]), Int64.Type),
				    ConNumeroDia = Table.AddColumn(ConDia, "NumeroDia", each Date.DayOfWeek([Fecha], Day.Monday), Int64.Type),
				    ConOrdenDia = Table.AddColumn(ConNumeroDia, "OrdenDia", each [NumeroDia] + 1, Int64.Type),
				    ConNombreDia = Table.AddColumn(ConOrdenDia, "NombreDia", each {"Lunes", "Martes", "Miercoles", "Jueves", "Viernes", "Sabado", "Domingo"}{[NumeroDia]}, type text),
				    ConSemana = Table.AddColumn(ConNombreDia, "Semana", each Date.WeekOfYear([Fecha], Day.Monday), Int64.Type)
				in
				    ConSemana

